/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getAddressEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type Option,
  type OptionOrNullable,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";
import {
  expectAddress,
  expectSome,
  getAccountMetaFactory,
  type ResolvedAccount,
} from "../shared";

export const CREATE_GAME_DISCRIMINATOR = new Uint8Array([
  124, 69, 75, 66, 184, 220, 72, 206,
]);

export function getCreateGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(CREATE_GAME_DISCRIMINATOR);
}

export type CreateGameInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayerBoard extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPlayer extends string
        ? WritableSignerAccount<TAccountPlayer> &
            AccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayerBoard extends string
        ? WritableAccount<TAccountPlayerBoard>
        : TAccountPlayerBoard,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type CreateGameInstructionData = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  gridSize: number;
  wager: Option<bigint>;
};

export type CreateGameInstructionDataArgs = {
  id: number | bigint;
  gridSize: number;
  wager: OptionOrNullable<number | bigint>;
};

export function getCreateGameInstructionDataEncoder(): Encoder<CreateGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["id", getU64Encoder()],
      ["gridSize", getU8Encoder()],
      ["wager", getOptionEncoder(getU64Encoder())],
    ]),
    (value) => ({ ...value, discriminator: CREATE_GAME_DISCRIMINATOR }),
  );
}

export function getCreateGameInstructionDataDecoder(): Decoder<CreateGameInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["id", getU64Decoder()],
    ["gridSize", getU8Decoder()],
    ["wager", getOptionDecoder(getU64Decoder())],
  ]);
}

export function getCreateGameInstructionDataCodec(): Codec<
  CreateGameInstructionDataArgs,
  CreateGameInstructionData
> {
  return combineCodec(
    getCreateGameInstructionDataEncoder(),
    getCreateGameInstructionDataDecoder(),
  );
}

export type CreateGameAsyncInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
  TAccountConfig extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  game?: Address<TAccountGame>;
  playerBoard?: Address<TAccountPlayerBoard>;
  config?: Address<TAccountConfig>;
  vault?: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateGameInstructionDataArgs["id"];
  gridSize: CreateGameInstructionDataArgs["gridSize"];
  wager: CreateGameInstructionDataArgs["wager"];
};

export async function getCreateGameInstructionAsync<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TAccountConfig extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: CreateGameAsyncInput<
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  CreateGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.game.value) {
    accounts.game.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([103, 97, 109, 101])),
        getU64Encoder().encode(expectSome(args.id)),
      ],
    });
  }
  if (!accounts.playerBoard.value) {
    accounts.playerBoard.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([112, 108, 97, 121, 101, 114])),
        getU64Encoder().encode(expectSome(args.id)),
        getAddressEncoder().encode(expectAddress(accounts.player.value)),
      ],
    });
  }
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateGameInstructionDataEncoder().encode(
      args as CreateGameInstructionDataArgs,
    ),
    programAddress,
  } as CreateGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type CreateGameInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
  TAccountConfig extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  game: Address<TAccountGame>;
  playerBoard: Address<TAccountPlayerBoard>;
  config: Address<TAccountConfig>;
  vault: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
  id: CreateGameInstructionDataArgs["id"];
  gridSize: CreateGameInstructionDataArgs["gridSize"];
  wager: CreateGameInstructionDataArgs["wager"];
};

export function getCreateGameInstruction<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TAccountConfig extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: CreateGameInput<
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): CreateGameInstruction<
  TProgramAddress,
  TAccountPlayer,
  TAccountGame,
  TAccountPlayerBoard,
  TAccountConfig,
  TAccountVault,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: true },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getCreateGameInstructionDataEncoder().encode(
      args as CreateGameInstructionDataArgs,
    ),
    programAddress,
  } as CreateGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type ParsedCreateGameInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    player: TAccountMetas[0];
    game: TAccountMetas[1];
    playerBoard: TAccountMetas[2];
    config: TAccountMetas[3];
    vault: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: CreateGameInstructionData;
};

export function parseCreateGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedCreateGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      player: getNextAccount(),
      game: getNextAccount(),
      playerBoard: getNextAccount(),
      config: getNextAccount(),
      vault: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getCreateGameInstructionDataDecoder().decode(instruction.data),
  };
}
