/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";
import {
  getShipCoordinatesDecoder,
  getShipCoordinatesEncoder,
  type ShipCoordinates,
  type ShipCoordinatesArgs,
} from "../types";

export const HIDE_SHIPS_DISCRIMINATOR = new Uint8Array([
  51, 136, 140, 51, 235, 220, 133, 69,
]);

export function getHideShipsDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(HIDE_SHIPS_DISCRIMINATOR);
}

export type HideShipsInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayerBoard extends string | AccountMeta<string> = string,
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPlayer extends string
        ? WritableSignerAccount<TAccountPlayer> &
            AccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayerBoard extends string
        ? WritableAccount<TAccountPlayerBoard>
        : TAccountPlayerBoard,
      ...TRemainingAccounts,
    ]
  >;

export type HideShipsInstructionData = {
  discriminator: ReadonlyUint8Array;
  ships: Array<ShipCoordinates>;
};

export type HideShipsInstructionDataArgs = {
  ships: Array<ShipCoordinatesArgs>;
};

export function getHideShipsInstructionDataEncoder(): Encoder<HideShipsInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["ships", getArrayEncoder(getShipCoordinatesEncoder())],
    ]),
    (value) => ({ ...value, discriminator: HIDE_SHIPS_DISCRIMINATOR }),
  );
}

export function getHideShipsInstructionDataDecoder(): Decoder<HideShipsInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["ships", getArrayDecoder(getShipCoordinatesDecoder())],
  ]);
}

export function getHideShipsInstructionDataCodec(): Codec<
  HideShipsInstructionDataArgs,
  HideShipsInstructionData
> {
  return combineCodec(
    getHideShipsInstructionDataEncoder(),
    getHideShipsInstructionDataDecoder(),
  );
}

export type HideShipsInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  game: Address<TAccountGame>;
  playerBoard: Address<TAccountPlayerBoard>;
  ships: HideShipsInstructionDataArgs["ships"];
};

export function getHideShipsInstruction<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: HideShipsInput<TAccountPlayer, TAccountGame, TAccountPlayerBoard>,
  config?: { programAddress?: TProgramAddress },
): HideShipsInstruction<
  TProgramAddress,
  TAccountPlayer,
  TAccountGame,
  TAccountPlayerBoard
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: false },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
    ],
    data: getHideShipsInstructionDataEncoder().encode(
      args as HideShipsInstructionDataArgs,
    ),
    programAddress,
  } as HideShipsInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard
  >);
}

export type ParsedHideShipsInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    player: TAccountMetas[0];
    game: TAccountMetas[1];
    playerBoard: TAccountMetas[2];
  };
  data: HideShipsInstructionData;
};

export function parseHideShipsInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedHideShipsInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 3) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      player: getNextAccount(),
      game: getNextAccount(),
      playerBoard: getNextAccount(),
    },
    data: getHideShipsInstructionDataDecoder().decode(instruction.data),
  };
}
