/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getProgramDerivedAddress,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const JOIN_GAME_DISCRIMINATOR = new Uint8Array([
  107, 112, 18, 38, 56, 173, 60, 128,
]);

export function getJoinGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(JOIN_GAME_DISCRIMINATOR);
}

export type JoinGameInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayerBoard extends string | AccountMeta<string> = string,
  TAccountConfig extends string | AccountMeta<string> = string,
  TAccountVault extends string | AccountMeta<string> = string,
  TAccountSystemProgram extends string | AccountMeta<string> =
    "11111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPlayer extends string
        ? WritableSignerAccount<TAccountPlayer> &
            AccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountGame extends string
        ? ReadonlyAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayerBoard extends string
        ? WritableAccount<TAccountPlayerBoard>
        : TAccountPlayerBoard,
      TAccountConfig extends string
        ? ReadonlyAccount<TAccountConfig>
        : TAccountConfig,
      TAccountVault extends string
        ? WritableAccount<TAccountVault>
        : TAccountVault,
      TAccountSystemProgram extends string
        ? ReadonlyAccount<TAccountSystemProgram>
        : TAccountSystemProgram,
      ...TRemainingAccounts,
    ]
  >;

export type JoinGameInstructionData = { discriminator: ReadonlyUint8Array };

export type JoinGameInstructionDataArgs = {};

export function getJoinGameInstructionDataEncoder(): FixedSizeEncoder<JoinGameInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: JOIN_GAME_DISCRIMINATOR }),
  );
}

export function getJoinGameInstructionDataDecoder(): FixedSizeDecoder<JoinGameInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getJoinGameInstructionDataCodec(): FixedSizeCodec<
  JoinGameInstructionDataArgs,
  JoinGameInstructionData
> {
  return combineCodec(
    getJoinGameInstructionDataEncoder(),
    getJoinGameInstructionDataDecoder(),
  );
}

export type JoinGameAsyncInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
  TAccountConfig extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  game: Address<TAccountGame>;
  playerBoard: Address<TAccountPlayerBoard>;
  config?: Address<TAccountConfig>;
  vault?: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export async function getJoinGameInstructionAsync<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TAccountConfig extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: JoinGameAsyncInput<
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): Promise<
  JoinGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: false },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.config.value) {
    accounts.config.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([99, 111, 110, 102, 105, 103])),
      ],
    });
  }
  if (!accounts.vault.value) {
    accounts.vault.value = await getProgramDerivedAddress({
      programAddress,
      seeds: [
        getBytesEncoder().encode(new Uint8Array([118, 97, 117, 108, 116])),
      ],
    });
  }
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getJoinGameInstructionDataEncoder().encode({}),
    programAddress,
  } as JoinGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type JoinGameInput<
  TAccountPlayer extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
  TAccountConfig extends string = string,
  TAccountVault extends string = string,
  TAccountSystemProgram extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  game: Address<TAccountGame>;
  playerBoard: Address<TAccountPlayerBoard>;
  config: Address<TAccountConfig>;
  vault: Address<TAccountVault>;
  systemProgram?: Address<TAccountSystemProgram>;
};

export function getJoinGameInstruction<
  TAccountPlayer extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TAccountConfig extends string,
  TAccountVault extends string,
  TAccountSystemProgram extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: JoinGameInput<
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >,
  config?: { programAddress?: TProgramAddress },
): JoinGameInstruction<
  TProgramAddress,
  TAccountPlayer,
  TAccountGame,
  TAccountPlayerBoard,
  TAccountConfig,
  TAccountVault,
  TAccountSystemProgram
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    game: { value: input.game ?? null, isWritable: false },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
    config: { value: input.config ?? null, isWritable: false },
    vault: { value: input.vault ?? null, isWritable: true },
    systemProgram: { value: input.systemProgram ?? null, isWritable: false },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.systemProgram.value) {
    accounts.systemProgram.value =
      "11111111111111111111111111111111" as Address<"11111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
      getAccountMeta(accounts.config),
      getAccountMeta(accounts.vault),
      getAccountMeta(accounts.systemProgram),
    ],
    data: getJoinGameInstructionDataEncoder().encode({}),
    programAddress,
  } as JoinGameInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountConfig,
    TAccountVault,
    TAccountSystemProgram
  >);
}

export type ParsedJoinGameInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    player: TAccountMetas[0];
    game: TAccountMetas[1];
    playerBoard: TAccountMetas[2];
    config: TAccountMetas[3];
    vault: TAccountMetas[4];
    systemProgram: TAccountMetas[5];
  };
  data: JoinGameInstructionData;
};

export function parseJoinGameInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedJoinGameInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 6) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      player: getNextAccount(),
      game: getNextAccount(),
      playerBoard: getNextAccount(),
      config: getNextAccount(),
      vault: getNextAccount(),
      systemProgram: getNextAccount(),
    },
    data: getJoinGameInstructionDataDecoder().decode(instruction.data),
  };
}
