/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const MAKE_MOVE_DISCRIMINATOR = new Uint8Array([
  78, 77, 152, 203, 222, 211, 208, 233,
]);

export function getMakeMoveDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(MAKE_MOVE_DISCRIMINATOR);
}

export type MakeMoveInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountPlayer extends string | AccountMeta<string> = string,
  TAccountOpponent extends string | AccountMeta<string> = string,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayerBoard extends string | AccountMeta<string> = string,
  TAccountOpponentBoard extends string | AccountMeta<string> = string,
  TAccountMagicProgram extends string | AccountMeta<string> =
    "Magic11111111111111111111111111111111111111",
  TAccountMagicContext extends string | AccountMeta<string> =
    "MagicContext1111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountPlayer extends string
        ? WritableSignerAccount<TAccountPlayer> &
            AccountSignerMeta<TAccountPlayer>
        : TAccountPlayer,
      TAccountOpponent extends string
        ? ReadonlyAccount<TAccountOpponent>
        : TAccountOpponent,
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayerBoard extends string
        ? WritableAccount<TAccountPlayerBoard>
        : TAccountPlayerBoard,
      TAccountOpponentBoard extends string
        ? WritableAccount<TAccountOpponentBoard>
        : TAccountOpponentBoard,
      TAccountMagicProgram extends string
        ? ReadonlyAccount<TAccountMagicProgram>
        : TAccountMagicProgram,
      TAccountMagicContext extends string
        ? WritableAccount<TAccountMagicContext>
        : TAccountMagicContext,
      ...TRemainingAccounts,
    ]
  >;

export type MakeMoveInstructionData = {
  discriminator: ReadonlyUint8Array;
  x: number;
  y: number;
};

export type MakeMoveInstructionDataArgs = { x: number; y: number };

export function getMakeMoveInstructionDataEncoder(): FixedSizeEncoder<MakeMoveInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["x", getU8Encoder()],
      ["y", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: MAKE_MOVE_DISCRIMINATOR }),
  );
}

export function getMakeMoveInstructionDataDecoder(): FixedSizeDecoder<MakeMoveInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["x", getU8Decoder()],
    ["y", getU8Decoder()],
  ]);
}

export function getMakeMoveInstructionDataCodec(): FixedSizeCodec<
  MakeMoveInstructionDataArgs,
  MakeMoveInstructionData
> {
  return combineCodec(
    getMakeMoveInstructionDataEncoder(),
    getMakeMoveInstructionDataDecoder(),
  );
}

export type MakeMoveInput<
  TAccountPlayer extends string = string,
  TAccountOpponent extends string = string,
  TAccountGame extends string = string,
  TAccountPlayerBoard extends string = string,
  TAccountOpponentBoard extends string = string,
  TAccountMagicProgram extends string = string,
  TAccountMagicContext extends string = string,
> = {
  player: TransactionSigner<TAccountPlayer>;
  opponent: Address<TAccountOpponent>;
  game: Address<TAccountGame>;
  playerBoard: Address<TAccountPlayerBoard>;
  opponentBoard: Address<TAccountOpponentBoard>;
  magicProgram?: Address<TAccountMagicProgram>;
  magicContext?: Address<TAccountMagicContext>;
  x: MakeMoveInstructionDataArgs["x"];
  y: MakeMoveInstructionDataArgs["y"];
};

export function getMakeMoveInstruction<
  TAccountPlayer extends string,
  TAccountOpponent extends string,
  TAccountGame extends string,
  TAccountPlayerBoard extends string,
  TAccountOpponentBoard extends string,
  TAccountMagicProgram extends string,
  TAccountMagicContext extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: MakeMoveInput<
    TAccountPlayer,
    TAccountOpponent,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountOpponentBoard,
    TAccountMagicProgram,
    TAccountMagicContext
  >,
  config?: { programAddress?: TProgramAddress },
): MakeMoveInstruction<
  TProgramAddress,
  TAccountPlayer,
  TAccountOpponent,
  TAccountGame,
  TAccountPlayerBoard,
  TAccountOpponentBoard,
  TAccountMagicProgram,
  TAccountMagicContext
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    player: { value: input.player ?? null, isWritable: true },
    opponent: { value: input.opponent ?? null, isWritable: false },
    game: { value: input.game ?? null, isWritable: true },
    playerBoard: { value: input.playerBoard ?? null, isWritable: true },
    opponentBoard: { value: input.opponentBoard ?? null, isWritable: true },
    magicProgram: { value: input.magicProgram ?? null, isWritable: false },
    magicContext: { value: input.magicContext ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Original args.
  const args = { ...input };

  // Resolve default values.
  if (!accounts.magicProgram.value) {
    accounts.magicProgram.value =
      "Magic11111111111111111111111111111111111111" as Address<"Magic11111111111111111111111111111111111111">;
  }
  if (!accounts.magicContext.value) {
    accounts.magicContext.value =
      "MagicContext1111111111111111111111111111111" as Address<"MagicContext1111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.player),
      getAccountMeta(accounts.opponent),
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.playerBoard),
      getAccountMeta(accounts.opponentBoard),
      getAccountMeta(accounts.magicProgram),
      getAccountMeta(accounts.magicContext),
    ],
    data: getMakeMoveInstructionDataEncoder().encode(
      args as MakeMoveInstructionDataArgs,
    ),
    programAddress,
  } as MakeMoveInstruction<
    TProgramAddress,
    TAccountPlayer,
    TAccountOpponent,
    TAccountGame,
    TAccountPlayerBoard,
    TAccountOpponentBoard,
    TAccountMagicProgram,
    TAccountMagicContext
  >);
}

export type ParsedMakeMoveInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    player: TAccountMetas[0];
    opponent: TAccountMetas[1];
    game: TAccountMetas[2];
    playerBoard: TAccountMetas[3];
    opponentBoard: TAccountMetas[4];
    magicProgram: TAccountMetas[5];
    magicContext: TAccountMetas[6];
  };
  data: MakeMoveInstructionData;
};

export function parseMakeMoveInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedMakeMoveInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 7) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      player: getNextAccount(),
      opponent: getNextAccount(),
      game: getNextAccount(),
      playerBoard: getNextAccount(),
      opponentBoard: getNextAccount(),
      magicProgram: getNextAccount(),
      magicContext: getNextAccount(),
    },
    data: getMakeMoveInstructionDataDecoder().decode(instruction.data),
  };
}
