/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  fixDecoderSize,
  fixEncoderSize,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  transformEncoder,
  type AccountMeta,
  type AccountSignerMeta,
  type Address,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
  type Instruction,
  type InstructionWithAccounts,
  type InstructionWithData,
  type ReadonlyAccount,
  type ReadonlyUint8Array,
  type TransactionSigner,
  type WritableAccount,
  type WritableSignerAccount,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";
import { getAccountMetaFactory, type ResolvedAccount } from "../shared";

export const REVEAL_WINNER_DISCRIMINATOR = new Uint8Array([
  234, 209, 237, 109, 16, 196, 64, 254,
]);

export function getRevealWinnerDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    REVEAL_WINNER_DISCRIMINATOR,
  );
}

export type RevealWinnerInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountGame extends string | AccountMeta<string> = string,
  TAccountPlayer1Board extends string | AccountMeta<string> = string,
  TAccountPlayer2Board extends string | AccountMeta<string> = string,
  TAccountPermission1 extends string | AccountMeta<string> = string,
  TAccountPermission2 extends string | AccountMeta<string> = string,
  TAccountPayer extends string | AccountMeta<string> = string,
  TAccountPermissionProgram extends string | AccountMeta<string> =
    "ACLseoPoyC3cBqoUtkbjZ4aDrkurZW86v19pXz2XQnp1",
  TAccountMagicProgram extends string | AccountMeta<string> =
    "Magic11111111111111111111111111111111111111",
  TAccountMagicContext extends string | AccountMeta<string> =
    "MagicContext1111111111111111111111111111111",
  TRemainingAccounts extends readonly AccountMeta<string>[] = [],
> = Instruction<TProgram> &
  InstructionWithData<ReadonlyUint8Array> &
  InstructionWithAccounts<
    [
      TAccountGame extends string
        ? WritableAccount<TAccountGame>
        : TAccountGame,
      TAccountPlayer1Board extends string
        ? WritableAccount<TAccountPlayer1Board>
        : TAccountPlayer1Board,
      TAccountPlayer2Board extends string
        ? WritableAccount<TAccountPlayer2Board>
        : TAccountPlayer2Board,
      TAccountPermission1 extends string
        ? WritableAccount<TAccountPermission1>
        : TAccountPermission1,
      TAccountPermission2 extends string
        ? WritableAccount<TAccountPermission2>
        : TAccountPermission2,
      TAccountPayer extends string
        ? WritableSignerAccount<TAccountPayer> &
            AccountSignerMeta<TAccountPayer>
        : TAccountPayer,
      TAccountPermissionProgram extends string
        ? ReadonlyAccount<TAccountPermissionProgram>
        : TAccountPermissionProgram,
      TAccountMagicProgram extends string
        ? ReadonlyAccount<TAccountMagicProgram>
        : TAccountMagicProgram,
      TAccountMagicContext extends string
        ? WritableAccount<TAccountMagicContext>
        : TAccountMagicContext,
      ...TRemainingAccounts,
    ]
  >;

export type RevealWinnerInstructionData = { discriminator: ReadonlyUint8Array };

export type RevealWinnerInstructionDataArgs = {};

export function getRevealWinnerInstructionDataEncoder(): FixedSizeEncoder<RevealWinnerInstructionDataArgs> {
  return transformEncoder(
    getStructEncoder([["discriminator", fixEncoderSize(getBytesEncoder(), 8)]]),
    (value) => ({ ...value, discriminator: REVEAL_WINNER_DISCRIMINATOR }),
  );
}

export function getRevealWinnerInstructionDataDecoder(): FixedSizeDecoder<RevealWinnerInstructionData> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
  ]);
}

export function getRevealWinnerInstructionDataCodec(): FixedSizeCodec<
  RevealWinnerInstructionDataArgs,
  RevealWinnerInstructionData
> {
  return combineCodec(
    getRevealWinnerInstructionDataEncoder(),
    getRevealWinnerInstructionDataDecoder(),
  );
}

export type RevealWinnerInput<
  TAccountGame extends string = string,
  TAccountPlayer1Board extends string = string,
  TAccountPlayer2Board extends string = string,
  TAccountPermission1 extends string = string,
  TAccountPermission2 extends string = string,
  TAccountPayer extends string = string,
  TAccountPermissionProgram extends string = string,
  TAccountMagicProgram extends string = string,
  TAccountMagicContext extends string = string,
> = {
  game: Address<TAccountGame>;
  player1Board: Address<TAccountPlayer1Board>;
  player2Board: Address<TAccountPlayer2Board>;
  permission1: Address<TAccountPermission1>;
  permission2: Address<TAccountPermission2>;
  payer: TransactionSigner<TAccountPayer>;
  permissionProgram?: Address<TAccountPermissionProgram>;
  magicProgram?: Address<TAccountMagicProgram>;
  magicContext?: Address<TAccountMagicContext>;
};

export function getRevealWinnerInstruction<
  TAccountGame extends string,
  TAccountPlayer1Board extends string,
  TAccountPlayer2Board extends string,
  TAccountPermission1 extends string,
  TAccountPermission2 extends string,
  TAccountPayer extends string,
  TAccountPermissionProgram extends string,
  TAccountMagicProgram extends string,
  TAccountMagicContext extends string,
  TProgramAddress extends Address = typeof CAYED_PROGRAM_ADDRESS,
>(
  input: RevealWinnerInput<
    TAccountGame,
    TAccountPlayer1Board,
    TAccountPlayer2Board,
    TAccountPermission1,
    TAccountPermission2,
    TAccountPayer,
    TAccountPermissionProgram,
    TAccountMagicProgram,
    TAccountMagicContext
  >,
  config?: { programAddress?: TProgramAddress },
): RevealWinnerInstruction<
  TProgramAddress,
  TAccountGame,
  TAccountPlayer1Board,
  TAccountPlayer2Board,
  TAccountPermission1,
  TAccountPermission2,
  TAccountPayer,
  TAccountPermissionProgram,
  TAccountMagicProgram,
  TAccountMagicContext
> {
  // Program address.
  const programAddress = config?.programAddress ?? CAYED_PROGRAM_ADDRESS;

  // Original accounts.
  const originalAccounts = {
    game: { value: input.game ?? null, isWritable: true },
    player1Board: { value: input.player1Board ?? null, isWritable: true },
    player2Board: { value: input.player2Board ?? null, isWritable: true },
    permission1: { value: input.permission1 ?? null, isWritable: true },
    permission2: { value: input.permission2 ?? null, isWritable: true },
    payer: { value: input.payer ?? null, isWritable: true },
    permissionProgram: {
      value: input.permissionProgram ?? null,
      isWritable: false,
    },
    magicProgram: { value: input.magicProgram ?? null, isWritable: false },
    magicContext: { value: input.magicContext ?? null, isWritable: true },
  };
  const accounts = originalAccounts as Record<
    keyof typeof originalAccounts,
    ResolvedAccount
  >;

  // Resolve default values.
  if (!accounts.permissionProgram.value) {
    accounts.permissionProgram.value =
      "ACLseoPoyC3cBqoUtkbjZ4aDrkurZW86v19pXz2XQnp1" as Address<"ACLseoPoyC3cBqoUtkbjZ4aDrkurZW86v19pXz2XQnp1">;
  }
  if (!accounts.magicProgram.value) {
    accounts.magicProgram.value =
      "Magic11111111111111111111111111111111111111" as Address<"Magic11111111111111111111111111111111111111">;
  }
  if (!accounts.magicContext.value) {
    accounts.magicContext.value =
      "MagicContext1111111111111111111111111111111" as Address<"MagicContext1111111111111111111111111111111">;
  }

  const getAccountMeta = getAccountMetaFactory(programAddress, "programId");
  return Object.freeze({
    accounts: [
      getAccountMeta(accounts.game),
      getAccountMeta(accounts.player1Board),
      getAccountMeta(accounts.player2Board),
      getAccountMeta(accounts.permission1),
      getAccountMeta(accounts.permission2),
      getAccountMeta(accounts.payer),
      getAccountMeta(accounts.permissionProgram),
      getAccountMeta(accounts.magicProgram),
      getAccountMeta(accounts.magicContext),
    ],
    data: getRevealWinnerInstructionDataEncoder().encode({}),
    programAddress,
  } as RevealWinnerInstruction<
    TProgramAddress,
    TAccountGame,
    TAccountPlayer1Board,
    TAccountPlayer2Board,
    TAccountPermission1,
    TAccountPermission2,
    TAccountPayer,
    TAccountPermissionProgram,
    TAccountMagicProgram,
    TAccountMagicContext
  >);
}

export type ParsedRevealWinnerInstruction<
  TProgram extends string = typeof CAYED_PROGRAM_ADDRESS,
  TAccountMetas extends readonly AccountMeta[] = readonly AccountMeta[],
> = {
  programAddress: Address<TProgram>;
  accounts: {
    game: TAccountMetas[0];
    player1Board: TAccountMetas[1];
    player2Board: TAccountMetas[2];
    permission1: TAccountMetas[3];
    permission2: TAccountMetas[4];
    payer: TAccountMetas[5];
    permissionProgram: TAccountMetas[6];
    magicProgram: TAccountMetas[7];
    magicContext: TAccountMetas[8];
  };
  data: RevealWinnerInstructionData;
};

export function parseRevealWinnerInstruction<
  TProgram extends string,
  TAccountMetas extends readonly AccountMeta[],
>(
  instruction: Instruction<TProgram> &
    InstructionWithAccounts<TAccountMetas> &
    InstructionWithData<ReadonlyUint8Array>,
): ParsedRevealWinnerInstruction<TProgram, TAccountMetas> {
  if (instruction.accounts.length < 9) {
    // TODO: Coded error.
    throw new Error("Not enough accounts");
  }
  let accountIndex = 0;
  const getNextAccount = () => {
    const accountMeta = (instruction.accounts as TAccountMetas)[accountIndex]!;
    accountIndex += 1;
    return accountMeta;
  };
  return {
    programAddress: instruction.programAddress,
    accounts: {
      game: getNextAccount(),
      player1Board: getNextAccount(),
      player2Board: getNextAccount(),
      permission1: getNextAccount(),
      permission2: getNextAccount(),
      payer: getNextAccount(),
      permissionProgram: getNextAccount(),
      magicProgram: getNextAccount(),
      magicContext: getNextAccount(),
    },
    data: getRevealWinnerInstructionDataDecoder().decode(instruction.data),
  };
}
