/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getAddressDecoder,
  getAddressEncoder,
  getDiscriminatedUnionDecoder,
  getDiscriminatedUnionEncoder,
  getStructDecoder,
  getStructEncoder,
  getUnitDecoder,
  getUnitEncoder,
  type Address,
  type Codec,
  type Decoder,
  type Encoder,
  type GetDiscriminatedUnionVariant,
  type GetDiscriminatedUnionVariantContent,
} from "@solana/kit";

export type GameStatus =
  | { __kind: "AwaitingPlayerTwo" }
  | { __kind: "HidingShips" }
  | { __kind: "InProgress" }
  | { __kind: "Cancelled" }
  | { __kind: "Completed"; winner: Address }
  | { __kind: "Forfeited"; winner: Address }
  | { __kind: "WinnerRevealed"; winner: Address };

export type GameStatusArgs = GameStatus;

export function getGameStatusEncoder(): Encoder<GameStatusArgs> {
  return getDiscriminatedUnionEncoder([
    ["AwaitingPlayerTwo", getUnitEncoder()],
    ["HidingShips", getUnitEncoder()],
    ["InProgress", getUnitEncoder()],
    ["Cancelled", getUnitEncoder()],
    ["Completed", getStructEncoder([["winner", getAddressEncoder()]])],
    ["Forfeited", getStructEncoder([["winner", getAddressEncoder()]])],
    ["WinnerRevealed", getStructEncoder([["winner", getAddressEncoder()]])],
  ]);
}

export function getGameStatusDecoder(): Decoder<GameStatus> {
  return getDiscriminatedUnionDecoder([
    ["AwaitingPlayerTwo", getUnitDecoder()],
    ["HidingShips", getUnitDecoder()],
    ["InProgress", getUnitDecoder()],
    ["Cancelled", getUnitDecoder()],
    ["Completed", getStructDecoder([["winner", getAddressDecoder()]])],
    ["Forfeited", getStructDecoder([["winner", getAddressDecoder()]])],
    ["WinnerRevealed", getStructDecoder([["winner", getAddressDecoder()]])],
  ]);
}

export function getGameStatusCodec(): Codec<GameStatusArgs, GameStatus> {
  return combineCodec(getGameStatusEncoder(), getGameStatusDecoder());
}

// Data Enum Helpers.
export function gameStatus(
  kind: "AwaitingPlayerTwo",
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "AwaitingPlayerTwo">;
export function gameStatus(
  kind: "HidingShips",
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "HidingShips">;
export function gameStatus(
  kind: "InProgress",
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "InProgress">;
export function gameStatus(
  kind: "Cancelled",
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "Cancelled">;
export function gameStatus(
  kind: "Completed",
  data: GetDiscriminatedUnionVariantContent<
    GameStatusArgs,
    "__kind",
    "Completed"
  >,
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "Completed">;
export function gameStatus(
  kind: "Forfeited",
  data: GetDiscriminatedUnionVariantContent<
    GameStatusArgs,
    "__kind",
    "Forfeited"
  >,
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "Forfeited">;
export function gameStatus(
  kind: "WinnerRevealed",
  data: GetDiscriminatedUnionVariantContent<
    GameStatusArgs,
    "__kind",
    "WinnerRevealed"
  >,
): GetDiscriminatedUnionVariant<GameStatusArgs, "__kind", "WinnerRevealed">;
export function gameStatus<K extends GameStatusArgs["__kind"], Data>(
  kind: K,
  data?: Data,
) {
  return Array.isArray(data)
    ? { __kind: kind, fields: data }
    : { __kind: kind, ...(data ?? {}) };
}

export function isGameStatus<K extends GameStatus["__kind"]>(
  kind: K,
  value: GameStatus,
): value is GameStatus & { __kind: K } {
  return value.__kind === kind;
}
