/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getBooleanDecoder,
  getBooleanEncoder,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type MoveResult = { x: number; y: number; isHit: boolean };

export type MoveResultArgs = MoveResult;

export function getMoveResultEncoder(): FixedSizeEncoder<MoveResultArgs> {
  return getStructEncoder([
    ["x", getU8Encoder()],
    ["y", getU8Encoder()],
    ["isHit", getBooleanEncoder()],
  ]);
}

export function getMoveResultDecoder(): FixedSizeDecoder<MoveResult> {
  return getStructDecoder([
    ["x", getU8Decoder()],
    ["y", getU8Decoder()],
    ["isHit", getBooleanDecoder()],
  ]);
}

export function getMoveResultCodec(): FixedSizeCodec<
  MoveResultArgs,
  MoveResult
> {
  return combineCodec(getMoveResultEncoder(), getMoveResultDecoder());
}
