/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  combineCodec,
  getStructDecoder,
  getStructEncoder,
  getU8Decoder,
  getU8Encoder,
  type FixedSizeCodec,
  type FixedSizeDecoder,
  type FixedSizeEncoder,
} from "@solana/kit";

export type ShipCoordinates = {
  startX: number;
  startY: number;
  endX: number;
  endY: number;
};

export type ShipCoordinatesArgs = ShipCoordinates;

export function getShipCoordinatesEncoder(): FixedSizeEncoder<ShipCoordinatesArgs> {
  return getStructEncoder([
    ["startX", getU8Encoder()],
    ["startY", getU8Encoder()],
    ["endX", getU8Encoder()],
    ["endY", getU8Encoder()],
  ]);
}

export function getShipCoordinatesDecoder(): FixedSizeDecoder<ShipCoordinates> {
  return getStructDecoder([
    ["startX", getU8Decoder()],
    ["startY", getU8Decoder()],
    ["endX", getU8Decoder()],
    ["endY", getU8Decoder()],
  ]);
}

export function getShipCoordinatesCodec(): FixedSizeCodec<
  ShipCoordinatesArgs,
  ShipCoordinates
> {
  return combineCodec(getShipCoordinatesEncoder(), getShipCoordinatesDecoder());
}
