/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";

/** Overflow: Number overflowed */
export const CAYED_ERROR__OVERFLOW = 0x1770; // 6000
/** Unauthorized: Not authorized to perform this action */
export const CAYED_ERROR__UNAUTHORIZED = 0x1771; // 6001
/** MaxGridSizeTooLarge: Max grid size cannot exceed 10 */
export const CAYED_ERROR__MAX_GRID_SIZE_TOO_LARGE = 0x1772; // 6002
/** MinimumWager: Wager was supplied but below minimum */
export const CAYED_ERROR__MINIMUM_WAGER = 0x1773; // 6003
/** GridNotEven: Grid size must be a positive multiple of 2 */
export const CAYED_ERROR__GRID_NOT_EVEN = 0x1774; // 6004
/** GridSizeTooLarge: Grid size exceeds the maximum allowed by config */
export const CAYED_ERROR__GRID_SIZE_TOO_LARGE = 0x1775; // 6005
/** CannotJoinSelfGame: Cannot join a game created by yourself */
export const CAYED_ERROR__CANNOT_JOIN_SELF_GAME = 0x1776; // 6006
/** GameFull: The game has already been joined by someone else */
export const CAYED_ERROR__GAME_FULL = 0x1777; // 6007
/** IncorrectShipsLen: Incorrect number of ships placed on grid (0.5 * grid) */
export const CAYED_ERROR__INCORRECT_SHIPS_LEN = 0x1778; // 6008
/** ShipsAlreadyPlaced: Ships have already been placed on this board */
export const CAYED_ERROR__SHIPS_ALREADY_PLACED = 0x1779; // 6009
/** InvalidShipPlacement: Ship coordinates are out of the grid bounds */
export const CAYED_ERROR__INVALID_SHIP_PLACEMENT = 0x177a; // 6010
/** ShipNotLinear: Ships must be horizontal or vertical, not diagonal or rectangular */
export const CAYED_ERROR__SHIP_NOT_LINEAR = 0x177b; // 6011
/** ShipCoordsReversed: Ship start coordinates must be <= end coordinates */
export const CAYED_ERROR__SHIP_COORDS_REVERSED = 0x177c; // 6012
/** ShipOverlap: Two or more ships occupy the same cell */
export const CAYED_ERROR__SHIP_OVERLAP = 0x177d; // 6013
/** GameNotStarted: Can't move game hasn't been joined by any player_2 */
export const CAYED_ERROR__GAME_NOT_STARTED = 0x177e; // 6014
/** InvalidTurn: Signer tried to make a move out of turn */
export const CAYED_ERROR__INVALID_TURN = 0x177f; // 6015
/** InvalidOpponent: Provided opponent account is incorrect */
export const CAYED_ERROR__INVALID_OPPONENT = 0x1780; // 6016
/** AttackOutOfBounds: Attack coordinates are out of the grid bounds */
export const CAYED_ERROR__ATTACK_OUT_OF_BOUNDS = 0x1781; // 6017
/** CellAlreadyAttacked: This cell has already been attacked */
export const CAYED_ERROR__CELL_ALREADY_ATTACKED = 0x1782; // 6018
/** ShipsNotPlaced: Ships have not been placed yet */
export const CAYED_ERROR__SHIPS_NOT_PLACED = 0x1783; // 6019
/** AllShipsSunk: You are trying to make a move when all your ships are sunken */
export const CAYED_ERROR__ALL_SHIPS_SUNK = 0x1784; // 6020
/** InvalidGameStatus: Game is not in the correct state for this action */
export const CAYED_ERROR__INVALID_GAME_STATUS = 0x1785; // 6021
/** NotAllShipsSunk: Not all ships have been sunk yet */
export const CAYED_ERROR__NOT_ALL_SHIPS_SUNK = 0x1786; // 6022

export type CayedError =
  | typeof CAYED_ERROR__ALL_SHIPS_SUNK
  | typeof CAYED_ERROR__ATTACK_OUT_OF_BOUNDS
  | typeof CAYED_ERROR__CANNOT_JOIN_SELF_GAME
  | typeof CAYED_ERROR__CELL_ALREADY_ATTACKED
  | typeof CAYED_ERROR__GAME_FULL
  | typeof CAYED_ERROR__GAME_NOT_STARTED
  | typeof CAYED_ERROR__GRID_NOT_EVEN
  | typeof CAYED_ERROR__GRID_SIZE_TOO_LARGE
  | typeof CAYED_ERROR__INCORRECT_SHIPS_LEN
  | typeof CAYED_ERROR__INVALID_GAME_STATUS
  | typeof CAYED_ERROR__INVALID_OPPONENT
  | typeof CAYED_ERROR__INVALID_SHIP_PLACEMENT
  | typeof CAYED_ERROR__INVALID_TURN
  | typeof CAYED_ERROR__MAX_GRID_SIZE_TOO_LARGE
  | typeof CAYED_ERROR__MINIMUM_WAGER
  | typeof CAYED_ERROR__NOT_ALL_SHIPS_SUNK
  | typeof CAYED_ERROR__OVERFLOW
  | typeof CAYED_ERROR__SHIP_COORDS_REVERSED
  | typeof CAYED_ERROR__SHIP_NOT_LINEAR
  | typeof CAYED_ERROR__SHIP_OVERLAP
  | typeof CAYED_ERROR__SHIPS_ALREADY_PLACED
  | typeof CAYED_ERROR__SHIPS_NOT_PLACED
  | typeof CAYED_ERROR__UNAUTHORIZED;

let cayedErrorMessages: Record<CayedError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  cayedErrorMessages = {
    [CAYED_ERROR__ALL_SHIPS_SUNK]: `You are trying to make a move when all your ships are sunken`,
    [CAYED_ERROR__ATTACK_OUT_OF_BOUNDS]: `Attack coordinates are out of the grid bounds`,
    [CAYED_ERROR__CANNOT_JOIN_SELF_GAME]: `Cannot join a game created by yourself`,
    [CAYED_ERROR__CELL_ALREADY_ATTACKED]: `This cell has already been attacked`,
    [CAYED_ERROR__GAME_FULL]: `The game has already been joined by someone else`,
    [CAYED_ERROR__GAME_NOT_STARTED]: `Can't move game hasn't been joined by any player_2`,
    [CAYED_ERROR__GRID_NOT_EVEN]: `Grid size must be a positive multiple of 2`,
    [CAYED_ERROR__GRID_SIZE_TOO_LARGE]: `Grid size exceeds the maximum allowed by config`,
    [CAYED_ERROR__INCORRECT_SHIPS_LEN]: `Incorrect number of ships placed on grid (0.5 * grid)`,
    [CAYED_ERROR__INVALID_GAME_STATUS]: `Game is not in the correct state for this action`,
    [CAYED_ERROR__INVALID_OPPONENT]: `Provided opponent account is incorrect`,
    [CAYED_ERROR__INVALID_SHIP_PLACEMENT]: `Ship coordinates are out of the grid bounds`,
    [CAYED_ERROR__INVALID_TURN]: `Signer tried to make a move out of turn`,
    [CAYED_ERROR__MAX_GRID_SIZE_TOO_LARGE]: `Max grid size cannot exceed 10`,
    [CAYED_ERROR__MINIMUM_WAGER]: `Wager was supplied but below minimum`,
    [CAYED_ERROR__NOT_ALL_SHIPS_SUNK]: `Not all ships have been sunk yet`,
    [CAYED_ERROR__OVERFLOW]: `Number overflowed`,
    [CAYED_ERROR__SHIP_COORDS_REVERSED]: `Ship start coordinates must be <= end coordinates`,
    [CAYED_ERROR__SHIP_NOT_LINEAR]: `Ships must be horizontal or vertical, not diagonal or rectangular`,
    [CAYED_ERROR__SHIP_OVERLAP]: `Two or more ships occupy the same cell`,
    [CAYED_ERROR__SHIPS_ALREADY_PLACED]: `Ships have already been placed on this board`,
    [CAYED_ERROR__SHIPS_NOT_PLACED]: `Ships have not been placed yet`,
    [CAYED_ERROR__UNAUTHORIZED]: `Not authorized to perform this action`,
  };
}

export function getCayedErrorMessage(code: CayedError): string {
  if (process.env.NODE_ENV !== "production") {
    return (cayedErrorMessages as Record<CayedError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isCayedError<TProgramErrorCode extends CayedError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    CAYED_PROGRAM_ADDRESS,
    code,
  );
}
