/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  isProgramError,
  type Address,
  type SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM,
  type SolanaError,
} from "@solana/kit";
import { CAYED_PROGRAM_ADDRESS } from "../programs";

/** Overflow: Number overflowed */
export const CAYED_ERROR__OVERFLOW = 0x1770; // 6000
/** MinimumWager: Wager was supplied but below minimum */
export const CAYED_ERROR__MINIMUM_WAGER = 0x1771; // 6001
/** CannotJoinSelfGame: Cannot join a game created by yourself */
export const CAYED_ERROR__CANNOT_JOIN_SELF_GAME = 0x1772; // 6002
/** GameFull: The game has already been joined by someone else */
export const CAYED_ERROR__GAME_FULL = 0x1773; // 6003

export type CayedError =
  | typeof CAYED_ERROR__CANNOT_JOIN_SELF_GAME
  | typeof CAYED_ERROR__GAME_FULL
  | typeof CAYED_ERROR__MINIMUM_WAGER
  | typeof CAYED_ERROR__OVERFLOW;

let cayedErrorMessages: Record<CayedError, string> | undefined;
if (process.env.NODE_ENV !== "production") {
  cayedErrorMessages = {
    [CAYED_ERROR__CANNOT_JOIN_SELF_GAME]: `Cannot join a game created by yourself`,
    [CAYED_ERROR__GAME_FULL]: `The game has already been joined by someone else`,
    [CAYED_ERROR__MINIMUM_WAGER]: `Wager was supplied but below minimum`,
    [CAYED_ERROR__OVERFLOW]: `Number overflowed`,
  };
}

export function getCayedErrorMessage(code: CayedError): string {
  if (process.env.NODE_ENV !== "production") {
    return (cayedErrorMessages as Record<CayedError, string>)[code];
  }

  return "Error message not available in production bundles.";
}

export function isCayedError<TProgramErrorCode extends CayedError>(
  error: unknown,
  transactionMessage: {
    instructions: Record<number, { programAddress: Address }>;
  },
  code?: TProgramErrorCode,
): error is SolanaError<typeof SOLANA_ERROR__INSTRUCTION_ERROR__CUSTOM> &
  Readonly<{ context: Readonly<{ code: TProgramErrorCode }> }> {
  return isProgramError<TProgramErrorCode>(
    error,
    transactionMessage,
    CAYED_PROGRAM_ADDRESS,
    code,
  );
}
