/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getAddressDecoder,
  getAddressEncoder,
  getArrayDecoder,
  getArrayEncoder,
  getBooleanDecoder,
  getBooleanEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getOptionDecoder,
  getOptionEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  getU8Decoder,
  getU8Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type Option,
  type OptionOrNullable,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getGameStatusDecoder,
  getGameStatusEncoder,
  getShipCoordinatesDecoder,
  getShipCoordinatesEncoder,
  type GameStatus,
  type GameStatusArgs,
  type ShipCoordinates,
  type ShipCoordinatesArgs,
} from "../types";

export const GAME_DISCRIMINATOR = new Uint8Array([
  27, 90, 166, 125, 74, 100, 121, 18,
]);

export function getGameDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(GAME_DISCRIMINATOR);
}

export type Game = {
  discriminator: ReadonlyUint8Array;
  id: bigint;
  gridSize: number;
  player1: Address;
  player2: Option<Address>;
  revealedShipsPlayer1: Array<ShipCoordinates>;
  revealedShipsPlayer2: Array<ShipCoordinates>;
  nextMovePlayer1: boolean;
  wager: Option<bigint>;
  status: GameStatus;
  creatorPubkey: Address;
  bump: number;
};

export type GameArgs = {
  id: number | bigint;
  gridSize: number;
  player1: Address;
  player2: OptionOrNullable<Address>;
  revealedShipsPlayer1: Array<ShipCoordinatesArgs>;
  revealedShipsPlayer2: Array<ShipCoordinatesArgs>;
  nextMovePlayer1: boolean;
  wager: OptionOrNullable<number | bigint>;
  status: GameStatusArgs;
  creatorPubkey: Address;
  bump: number;
};

/** Gets the encoder for {@link GameArgs} account data. */
export function getGameEncoder(): Encoder<GameArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["id", getU64Encoder()],
      ["gridSize", getU8Encoder()],
      ["player1", getAddressEncoder()],
      ["player2", getOptionEncoder(getAddressEncoder())],
      ["revealedShipsPlayer1", getArrayEncoder(getShipCoordinatesEncoder())],
      ["revealedShipsPlayer2", getArrayEncoder(getShipCoordinatesEncoder())],
      ["nextMovePlayer1", getBooleanEncoder()],
      ["wager", getOptionEncoder(getU64Encoder())],
      ["status", getGameStatusEncoder()],
      ["creatorPubkey", getAddressEncoder()],
      ["bump", getU8Encoder()],
    ]),
    (value) => ({ ...value, discriminator: GAME_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link Game} account data. */
export function getGameDecoder(): Decoder<Game> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["id", getU64Decoder()],
    ["gridSize", getU8Decoder()],
    ["player1", getAddressDecoder()],
    ["player2", getOptionDecoder(getAddressDecoder())],
    ["revealedShipsPlayer1", getArrayDecoder(getShipCoordinatesDecoder())],
    ["revealedShipsPlayer2", getArrayDecoder(getShipCoordinatesDecoder())],
    ["nextMovePlayer1", getBooleanDecoder()],
    ["wager", getOptionDecoder(getU64Decoder())],
    ["status", getGameStatusDecoder()],
    ["creatorPubkey", getAddressDecoder()],
    ["bump", getU8Decoder()],
  ]);
}

/** Gets the codec for {@link Game} account data. */
export function getGameCodec(): Codec<GameArgs, Game> {
  return combineCodec(getGameEncoder(), getGameDecoder());
}

export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<Game, TAddress>;
export function decodeGame<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<Game, TAddress> | MaybeAccount<Game, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getGameDecoder(),
  );
}

export async function fetchGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<Game, TAddress>> {
  const maybeAccount = await fetchMaybeGame(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybeGame<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<Game, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodeGame(maybeAccount);
}

export async function fetchAllGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<Game>[]> {
  const maybeAccounts = await fetchAllMaybeGame(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybeGame(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<Game>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodeGame(maybeAccount));
}
