/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertAccountExists,
  assertAccountsExist,
  combineCodec,
  decodeAccount,
  fetchEncodedAccount,
  fetchEncodedAccounts,
  fixDecoderSize,
  fixEncoderSize,
  getArrayDecoder,
  getArrayEncoder,
  getBytesDecoder,
  getBytesEncoder,
  getStructDecoder,
  getStructEncoder,
  getU64Decoder,
  getU64Encoder,
  transformEncoder,
  type Account,
  type Address,
  type Codec,
  type Decoder,
  type EncodedAccount,
  type Encoder,
  type FetchAccountConfig,
  type FetchAccountsConfig,
  type MaybeAccount,
  type MaybeEncodedAccount,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  getShipCoordinatesDecoder,
  getShipCoordinatesEncoder,
  type ShipCoordinates,
  type ShipCoordinatesArgs,
} from "../types";

export const PLAYER_BOARD_DISCRIMINATOR = new Uint8Array([
  120, 6, 158, 230, 127, 175, 86, 173,
]);

export function getPlayerBoardDiscriminatorBytes() {
  return fixEncoderSize(getBytesEncoder(), 8).encode(
    PLAYER_BOARD_DISCRIMINATOR,
  );
}

export type PlayerBoard = {
  discriminator: ReadonlyUint8Array;
  gameId: bigint;
  shipCoordinates: Array<ShipCoordinates>;
};

export type PlayerBoardArgs = {
  gameId: number | bigint;
  shipCoordinates: Array<ShipCoordinatesArgs>;
};

/** Gets the encoder for {@link PlayerBoardArgs} account data. */
export function getPlayerBoardEncoder(): Encoder<PlayerBoardArgs> {
  return transformEncoder(
    getStructEncoder([
      ["discriminator", fixEncoderSize(getBytesEncoder(), 8)],
      ["gameId", getU64Encoder()],
      ["shipCoordinates", getArrayEncoder(getShipCoordinatesEncoder())],
    ]),
    (value) => ({ ...value, discriminator: PLAYER_BOARD_DISCRIMINATOR }),
  );
}

/** Gets the decoder for {@link PlayerBoard} account data. */
export function getPlayerBoardDecoder(): Decoder<PlayerBoard> {
  return getStructDecoder([
    ["discriminator", fixDecoderSize(getBytesDecoder(), 8)],
    ["gameId", getU64Decoder()],
    ["shipCoordinates", getArrayDecoder(getShipCoordinatesDecoder())],
  ]);
}

/** Gets the codec for {@link PlayerBoard} account data. */
export function getPlayerBoardCodec(): Codec<PlayerBoardArgs, PlayerBoard> {
  return combineCodec(getPlayerBoardEncoder(), getPlayerBoardDecoder());
}

export function decodePlayerBoard<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress>,
): Account<PlayerBoard, TAddress>;
export function decodePlayerBoard<TAddress extends string = string>(
  encodedAccount: MaybeEncodedAccount<TAddress>,
): MaybeAccount<PlayerBoard, TAddress>;
export function decodePlayerBoard<TAddress extends string = string>(
  encodedAccount: EncodedAccount<TAddress> | MaybeEncodedAccount<TAddress>,
): Account<PlayerBoard, TAddress> | MaybeAccount<PlayerBoard, TAddress> {
  return decodeAccount(
    encodedAccount as MaybeEncodedAccount<TAddress>,
    getPlayerBoardDecoder(),
  );
}

export async function fetchPlayerBoard<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<Account<PlayerBoard, TAddress>> {
  const maybeAccount = await fetchMaybePlayerBoard(rpc, address, config);
  assertAccountExists(maybeAccount);
  return maybeAccount;
}

export async function fetchMaybePlayerBoard<TAddress extends string = string>(
  rpc: Parameters<typeof fetchEncodedAccount>[0],
  address: Address<TAddress>,
  config?: FetchAccountConfig,
): Promise<MaybeAccount<PlayerBoard, TAddress>> {
  const maybeAccount = await fetchEncodedAccount(rpc, address, config);
  return decodePlayerBoard(maybeAccount);
}

export async function fetchAllPlayerBoard(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<Account<PlayerBoard>[]> {
  const maybeAccounts = await fetchAllMaybePlayerBoard(rpc, addresses, config);
  assertAccountsExist(maybeAccounts);
  return maybeAccounts;
}

export async function fetchAllMaybePlayerBoard(
  rpc: Parameters<typeof fetchEncodedAccounts>[0],
  addresses: Array<Address>,
  config?: FetchAccountsConfig,
): Promise<MaybeAccount<PlayerBoard>[]> {
  const maybeAccounts = await fetchEncodedAccounts(rpc, addresses, config);
  return maybeAccounts.map((maybeAccount) => decodePlayerBoard(maybeAccount));
}
