/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseCreateGameInstruction,
  parseInitConfigInstruction,
  parseJoinGameInstruction,
  type ParsedCreateGameInstruction,
  type ParsedInitConfigInstruction,
  type ParsedJoinGameInstruction,
} from "../instructions";

export const CAYED_PROGRAM_ADDRESS =
  "3jatZuig82z7WWiKJmtzeiWoK2hxQnUwfAFNcJJPXAyN" as Address<"3jatZuig82z7WWiKJmtzeiWoK2hxQnUwfAFNcJJPXAyN">;

export enum CayedAccount {
  Config,
  Game,
  PlayerBoard,
}

export function identifyCayedAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CayedAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130]),
      ),
      0,
    )
  ) {
    return CayedAccount.Config;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 90, 166, 125, 74, 100, 121, 18]),
      ),
      0,
    )
  ) {
    return CayedAccount.Game;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([120, 6, 158, 230, 127, 175, 86, 173]),
      ),
      0,
    )
  ) {
    return CayedAccount.PlayerBoard;
  }
  throw new Error(
    "The provided account could not be identified as a cayed account.",
  );
}

export enum CayedInstruction {
  CreateGame,
  InitConfig,
  JoinGame,
}

export function identifyCayedInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CayedInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([124, 69, 75, 66, 184, 220, 72, 206]),
      ),
      0,
    )
  ) {
    return CayedInstruction.CreateGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([23, 235, 115, 232, 168, 96, 1, 231]),
      ),
      0,
    )
  ) {
    return CayedInstruction.InitConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([107, 112, 18, 38, 56, 173, 60, 128]),
      ),
      0,
    )
  ) {
    return CayedInstruction.JoinGame;
  }
  throw new Error(
    "The provided instruction could not be identified as a cayed instruction.",
  );
}

export type ParsedCayedInstruction<
  TProgram extends string = "3jatZuig82z7WWiKJmtzeiWoK2hxQnUwfAFNcJJPXAyN",
> =
  | ({
      instructionType: CayedInstruction.CreateGame;
    } & ParsedCreateGameInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.InitConfig;
    } & ParsedInitConfigInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.JoinGame;
    } & ParsedJoinGameInstruction<TProgram>);

export function parseCayedInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedCayedInstruction<TProgram> {
  const instructionType = identifyCayedInstruction(instruction);
  switch (instructionType) {
    case CayedInstruction.CreateGame: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.CreateGame,
        ...parseCreateGameInstruction(instruction),
      };
    }
    case CayedInstruction.InitConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.InitConfig,
        ...parseInitConfigInstruction(instruction),
      };
    }
    case CayedInstruction.JoinGame: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.JoinGame,
        ...parseJoinGameInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
