/**
 * This code was AUTOGENERATED using the Codama library.
 * Please DO NOT EDIT THIS FILE, instead use visitors
 * to add features, then rerun Codama to update it.
 *
 * @see https://github.com/codama-idl/codama
 */

import {
  assertIsInstructionWithAccounts,
  containsBytes,
  fixEncoderSize,
  getBytesEncoder,
  type Address,
  type Instruction,
  type InstructionWithData,
  type ReadonlyUint8Array,
} from "@solana/kit";
import {
  parseCreateGameInstruction,
  parseCreatePermissionInstruction,
  parseDelegatePdaInstruction,
  parseHideShipsInstruction,
  parseInitConfigInstruction,
  parseJoinGameInstruction,
  parseMakeMoveInstruction,
  parseProcessUndelegationInstruction,
  parseRevealWinnerInstruction,
  type ParsedCreateGameInstruction,
  type ParsedCreatePermissionInstruction,
  type ParsedDelegatePdaInstruction,
  type ParsedHideShipsInstruction,
  type ParsedInitConfigInstruction,
  type ParsedJoinGameInstruction,
  type ParsedMakeMoveInstruction,
  type ParsedProcessUndelegationInstruction,
  type ParsedRevealWinnerInstruction,
} from "../instructions";

export const CAYED_PROGRAM_ADDRESS =
  "6xLHbAHw2ibrmdVEPHm7jDkDmghw3fp3gUCBy511DMKV" as Address<"6xLHbAHw2ibrmdVEPHm7jDkDmghw3fp3gUCBy511DMKV">;

export enum CayedAccount {
  Config,
  Game,
  PlayerBoard,
  Vault,
}

export function identifyCayedAccount(
  account: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CayedAccount {
  const data = "data" in account ? account.data : account;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([155, 12, 170, 224, 30, 250, 204, 130]),
      ),
      0,
    )
  ) {
    return CayedAccount.Config;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([27, 90, 166, 125, 74, 100, 121, 18]),
      ),
      0,
    )
  ) {
    return CayedAccount.Game;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([120, 6, 158, 230, 127, 175, 86, 173]),
      ),
      0,
    )
  ) {
    return CayedAccount.PlayerBoard;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([211, 8, 232, 43, 2, 152, 117, 119]),
      ),
      0,
    )
  ) {
    return CayedAccount.Vault;
  }
  throw new Error(
    "The provided account could not be identified as a cayed account.",
  );
}

export enum CayedInstruction {
  CreateGame,
  CreatePermission,
  DelegatePda,
  HideShips,
  InitConfig,
  JoinGame,
  MakeMove,
  ProcessUndelegation,
  RevealWinner,
}

export function identifyCayedInstruction(
  instruction: { data: ReadonlyUint8Array } | ReadonlyUint8Array,
): CayedInstruction {
  const data = "data" in instruction ? instruction.data : instruction;
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([124, 69, 75, 66, 184, 220, 72, 206]),
      ),
      0,
    )
  ) {
    return CayedInstruction.CreateGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([190, 182, 26, 164, 156, 221, 8, 0]),
      ),
      0,
    )
  ) {
    return CayedInstruction.CreatePermission;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([248, 217, 193, 46, 124, 191, 64, 135]),
      ),
      0,
    )
  ) {
    return CayedInstruction.DelegatePda;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([51, 136, 140, 51, 235, 220, 133, 69]),
      ),
      0,
    )
  ) {
    return CayedInstruction.HideShips;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([23, 235, 115, 232, 168, 96, 1, 231]),
      ),
      0,
    )
  ) {
    return CayedInstruction.InitConfig;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([107, 112, 18, 38, 56, 173, 60, 128]),
      ),
      0,
    )
  ) {
    return CayedInstruction.JoinGame;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([78, 77, 152, 203, 222, 211, 208, 233]),
      ),
      0,
    )
  ) {
    return CayedInstruction.MakeMove;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([196, 28, 41, 206, 48, 37, 51, 167]),
      ),
      0,
    )
  ) {
    return CayedInstruction.ProcessUndelegation;
  }
  if (
    containsBytes(
      data,
      fixEncoderSize(getBytesEncoder(), 8).encode(
        new Uint8Array([234, 209, 237, 109, 16, 196, 64, 254]),
      ),
      0,
    )
  ) {
    return CayedInstruction.RevealWinner;
  }
  throw new Error(
    "The provided instruction could not be identified as a cayed instruction.",
  );
}

export type ParsedCayedInstruction<
  TProgram extends string = "6xLHbAHw2ibrmdVEPHm7jDkDmghw3fp3gUCBy511DMKV",
> =
  | ({
      instructionType: CayedInstruction.CreateGame;
    } & ParsedCreateGameInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.CreatePermission;
    } & ParsedCreatePermissionInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.DelegatePda;
    } & ParsedDelegatePdaInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.HideShips;
    } & ParsedHideShipsInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.InitConfig;
    } & ParsedInitConfigInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.JoinGame;
    } & ParsedJoinGameInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.MakeMove;
    } & ParsedMakeMoveInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.ProcessUndelegation;
    } & ParsedProcessUndelegationInstruction<TProgram>)
  | ({
      instructionType: CayedInstruction.RevealWinner;
    } & ParsedRevealWinnerInstruction<TProgram>);

export function parseCayedInstruction<TProgram extends string>(
  instruction: Instruction<TProgram> & InstructionWithData<ReadonlyUint8Array>,
): ParsedCayedInstruction<TProgram> {
  const instructionType = identifyCayedInstruction(instruction);
  switch (instructionType) {
    case CayedInstruction.CreateGame: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.CreateGame,
        ...parseCreateGameInstruction(instruction),
      };
    }
    case CayedInstruction.CreatePermission: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.CreatePermission,
        ...parseCreatePermissionInstruction(instruction),
      };
    }
    case CayedInstruction.DelegatePda: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.DelegatePda,
        ...parseDelegatePdaInstruction(instruction),
      };
    }
    case CayedInstruction.HideShips: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.HideShips,
        ...parseHideShipsInstruction(instruction),
      };
    }
    case CayedInstruction.InitConfig: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.InitConfig,
        ...parseInitConfigInstruction(instruction),
      };
    }
    case CayedInstruction.JoinGame: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.JoinGame,
        ...parseJoinGameInstruction(instruction),
      };
    }
    case CayedInstruction.MakeMove: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.MakeMove,
        ...parseMakeMoveInstruction(instruction),
      };
    }
    case CayedInstruction.ProcessUndelegation: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.ProcessUndelegation,
        ...parseProcessUndelegationInstruction(instruction),
      };
    }
    case CayedInstruction.RevealWinner: {
      assertIsInstructionWithAccounts(instruction);
      return {
        instructionType: CayedInstruction.RevealWinner,
        ...parseRevealWinnerInstruction(instruction),
      };
    }
    default:
      throw new Error(
        `Unrecognized instruction type: ${instructionType as string}`,
      );
  }
}
